let rutinaFlexibilidad = [
    {
        id: 'Fl0001',
        ejercicio: 'HOMBRO ROTACIÓN INTERNA',
        series: 2,
        repeticiones: 10,
        volumen_total: 20,
        descanso_entre_series: 30,
        video: 'https://youtu.be/UBkv7QTLhOA?si=hF3EHyBP1jkuG-Qb',
        video2: 'https://www.youtube.com/embed/UBkv7QTLhOA',
    },
    {
        id: 'Fl0002',
        ejercicio: 'PECTORAL CON HIPER EXTENSIÓN DE HOMBRO',
        series: 2,
        repeticiones: 10,
        volumen_total: 20,
        descanso_entre_series: 30,
        video: 'https://youtu.be/SJJs9IA65vA?si=KTdoAdEwLytr3UDo',
        video2: 'https://www.youtube.com/embed/SJJs9IA65vA',
    },
    {
        id: 'Fl0003',
        ejercicio: 'HOMBRO CON ADUCCIÓN HORIZONTAL',
        series: 2,
        repeticiones: 10,
        volumen_total: 20,
        descanso_entre_series: 30,
        video: 'https://youtu.be/UlZN4qAXHoo?si=QAc4PSbXI7sVgGes',
        video2: 'https://www.youtube.com/embed/UlZN4qAXHoo',
    },
    {
        id: 'Fl0004',
        ejercicio: 'GLUTEOS SENTADO EN BANCO',
        series: 2,
        repeticiones: 10,
        volumen_total: 20,
        descanso_entre_series: 30,
        video: 'https://youtu.be/Qf81vHwFM54?si=vGu_IpS5dE4qIYXd',
        video2: 'https://www.youtube.com/embed/Qf81vHwFM54',
    },
    {
        id: 'Fl0005',
        ejercicio: 'CONTRACCIÓN EN GUSANO',
        series: 2,
        repeticiones: 10,
        volumen_total: 20,
        descanso_entre_series: 30,
        video: 'https://youtu.be/osPeGVp4iRg?si=ur5h5jN2qQDZYenK',
        video2: 'https://www.youtube.com/embed/osPeGVp4iRg',
    },
    {
        id: 'Fl0006',
        ejercicio: 'EQUILIBRIO A UNA PIERNA',
        series: 2,
        repeticiones: 10,
        volumen_total: 20,
        descanso_entre_series: 30,
        video: 'https://youtu.be/Yc7PPKoiqvk?si=GuOJuFTztgL-ti8a',
        video2: 'https://www.youtube.com/embed/Yc7PPKoiqvk',
    },
    {
        id: 'Fl0007',
        ejercicio: 'PIRAMIDAL CON APOYO',
        series: 2,
        repeticiones: 10,
        volumen_total: 20,
        descanso_entre_series: 30,
        video: 'https://youtu.be/gNWpUMG-X74?si=VQwSuVBkIRGNoxkz',
        video2: 'https://www.youtube.com/embed/Yc7PPKoiqvk',
    },
    {
        id: 'Fl0008',
        ejercicio: 'NERVIO CIATICO SENTADADA CON PIERNAS ESTIRADAS',
        series: 2,
        repeticiones: 10,
        volumen_total: 20,
        descanso_entre_series: 30,
        video: 'https://youtu.be/Aj2t-xvL70s?si=evX4C1nsUT5QnVR2',
        video2: 'https://www.youtube.com/embed/Aj2t-xvL70s',
    },
    {
        id: 'Fl0009',
        ejercicio: 'EQUILIBRIO SOBRE UNA PIERNA',
        series: 2,
        repeticiones: 10,
        volumen_total: 20,
        descanso_entre_series: 30,
        video: 'https://youtu.be/HIjmx9X3WNo?si=n5hXIej94J-tYv8l',
        video2: 'https://www.youtube.com/embed/HIjmx9X3WNo',
    },
    {
        id: 'Fl0010',
        ejercicio: 'BAJADA ALTERNA DE UNA PIERNA FLEXIONADA A 90°',
        series: 2,
        repeticiones: 10,
        volumen_total: 20,
        descanso_entre_series: 30,
        video: 'https://youtu.be/jGX3bxjv5Eg?si=bg86P_q0hM28Ilxl',
        video2: 'https://www.youtube.com/embed/jGX3bxjv5Eg',
    },
    {
        id: 'Fl0011',
        ejercicio: 'BANDA ILIOTIBIAL DEL PIE',
        series: 2,
        repeticiones: 5,
        volumen_total: 10,
        descanso_entre_series: 30,
        video: 'https://youtu.be/NoVttpb5hxA?si=0rFVkoZFkPM0cj7q',
        video2: 'https://www.youtube.com/embed/NoVttpb5hxA',
    },
    {
        id: 'Fl0012',
        ejercicio: 'FLEXIÓN DE CADERA Y ROTACIÓN DE TRONCO',
        series: 2,
        repeticiones: 10,
        volumen_total: 20,
        descanso_entre_series: 30,
        video: 'https://youtu.be/oVgLvBL-CZE?si=zTza3nA9SWypKJGe',
        video2: 'https://www.youtube.com/watch?v=oVgLvBL-CZE',
    },
    {
        id: 'Fl0013',
        ejercicio: 'RETRACICIÓN ESCAPULAR',
        series: 2,
        repeticiones: 10,
        volumen_total: 20,
        descanso_entre_series: 30,
        video: 'https://youtu.be/eQnA25behdk?si=ImRTl_L5ERBK3BkV',
        video2: 'https://www.youtube.com/embed/eQnA25behdk',
    },
];


export {
    rutinaFlexibilidad
}
