
let rutinaFuerza = [
    {
        id: 'F0001',
        dia: 1,
        ejercicio: 'REMO AL CUELLO CON BARRA',
        series: 4,
        repeticiones: 20,
        volumen_total: 80,
        descanso_entre_series: 60, // segundos
        video: 'https://youtu.be/aDWOOg6XyEM?si=rlWdbct-aDideStx',
        video2: 'https://www.youtube.com/embed/aDWOOg6XyEM',
    },
    {
        id: 'F0002',
        dia: 1,
        ejercicio: 'MEDIA SENTADILLA EN EXTENSIÓN BRAZOS CON MANCUERNAS',
        series: 4,
        repeticiones: 15,
        volumen_total: 60,
        descanso_entre_series: 60,
        video: 'https://youtu.be/k7qCSkflpq0?si=LJUsL0MiPuuarwgM',
        video2: 'https://www.youtube.com/embed/k7qCSkflpq0',
    },
    {
        id: 'F0003',
        dia: 1,
        ejercicio: 'ZANCADA LATERAL CON MANCUERNAS',
        series: 4,
        repeticiones: 15,
        volumen_total: 60,
        descanso_entre_series: 60,
        video: 'https://youtu.be/7Be-fuAeL7A?si=CT8Bwqwd9Y3FT09F',
        video2: 'https://www.youtube.com/embed/7Be-fuAeL7A',
    },
    {
        id: 'F0004',
        dia: 1,
        ejercicio: 'BAJAR ESCALON CON UNA PIERNA',
        series: 4,
        repeticiones: 20,
        volumen_total: 80,
        descanso_entre_series: 60,
        video: 'https://youtu.be/aDWOOg6XyEM?si=rlWdbct-aDideStx',
        video2: 'https://www.youtube.com/embed/aDWOOg6XyEM',
    },
    {
        id: 'F0005',
        dia: 1,
        ejercicio: 'MEDIA SENTADILLA Y ELEVACIÓN DE GEMELOS',
        series: 4,
        repeticiones: 12,
        volumen_total: 48,
        descanso_entre_series: 60,
        video: 'https://youtu.be/7OhLQ68SaaQ?si=j3oQ24a-FGpj_53K',
        video2: 'https://www.youtube.com/embed/7OhLQ68SaaQ',
    },
    {
        id: 'F0006',
        dia: 1,
        ejercicio: 'SUBIR AL BANCO CON MANCUERNAS',
        series: 4,
        repeticiones: 15,
        volumen_total: 60,
        descanso_entre_series: 60,
        video: 'https://youtu.be/7Be-fuAeL7A?si=CT8Bwqwd9Y3FT09F',
        video2: 'https://www.youtube.com/embed/WJM6OKRxqq4',
    },
    {
        id: 'F0007',
        dia: 2,
        ejercicio: 'PRESS DE HOMBRO EN BANCA CON MANCUERNAS',
        series: 3,
        repeticiones: 10,
        volumen_total: 30,
        descanso_entre_series: 60,
        video: 'https://youtu.be/WUwCQ40btMQ?si=F3OxTgtpeBXS5qzT',
        video2: 'https://www.youtube.com/embed/WUwCQ40btMQ',
    },
    {
        id: 'F0008',
        dia: 2,
        ejercicio: 'KETTLEBELL EL MOLINO',
        series: 3,
        repeticiones: 10,
        volumen_total: 30,
        descanso_entre_series: 60,
        video: 'https://youtu.be/FzzMq9XYO3s?si=l9YkBdC3VnljU3HF',
        video2: 'https://www.youtube.com/embed/FzzMq9XYO3s',
    },
    {
        id: 'F0009',
        dia: 2,
        ejercicio: 'ELEVACIÓN DE HOMBROS EN PLANO DE LA ESCAPULA',
        series: 3,
        repeticiones: 10,
        volumen_total: 30,
        descanso_entre_series: 60,
        video: 'https://youtu.be/Q5m5SRZoWgw?si=XDzxhVemfEnwsC1z',
        video2: 'https://www.youtube.com/embed/Q5m5SRZoWgw',
    },
    {
        id: 'F0010',
        dia: 2,
        ejercicio: 'REMO DE PIE CON BANDA ELASTICA',
        series: 3,
        repeticiones: 10,
        volumen_total: 30,
        descanso_entre_series: 60,
        video: 'https://youtu.be/cRmuo81YQes?si=0iM6Ll41TolNg8IM',
        video2: 'https://www.youtube.com/embed/cRmuo81YQes',
    },
    {
        id: 'F0011',
        dia: 2,
        ejercicio: 'APERTURA DE HOMBROS CON BANDA ELASTICA',
        series: 3,
        repeticiones: 15,
        volumen_total: 45,
        descanso_entre_series: 60,
        video: 'https://youtu.be/sf1csHW-0R4?si=PYXiU_hWc0zb9q7i',
        video2: 'https://www.youtube.com/embed/sf1csHW-0R4',
    },
    {
        id: 'F0012',
        dia: 2,
        ejercicio: 'FLEXIÓN DE BRAZO',
        series: 3,
        repeticiones: 10,
        volumen_total: 30,
        descanso_entre_series: 60,
        video: 'https://youtu.be/NiElkGUcAPY?si=MWLeXoGPWGQI_IuZ',
        video2: 'https://www.youtube.com/embed/NiElkGUcAPY',
    },
    {
        id: 'F0013',
        dia: 3,
        ejercicio: 'FLEXION DE CADERA SUJETANDO BALÓN',
        series: 3,
        repeticiones: 10,
        volumen_total: 30,
        descanso_entre_series: 60,
        video: 'https://youtu.be/FkJu3fc3wCQ?si=UKg2ZekJsnzLIzhR',
        video2: 'https://www.youtube.com/watch?v=FkJu3fc3wCQ',
    },
    {
        id: 'F0014',
        dia: 3,
        ejercicio: 'MOVIMIENTO SOBRE STEP EN POSICIÓN DE FLEXIÓN DE BRAZOS',
        series: 3,
        repeticiones: 10,
        volumen_total: 30,
        descanso_entre_series: 60,
        video: 'https://youtu.be/8S6wPiYDuy4?si=F_9QqNX7rzu_DIFI',
        video2: 'https://www.youtube.com/embed/8S6wPiYDuy4',
    },
    {
        id: 'F0015',
        dia: 3,
        ejercicio: 'EXTENSIÓN DEL CUERPO SOBRE RODILLAS',
        series: 3,
        repeticiones: 10,
        volumen_total: 30,
        descanso_entre_series: 60,
        video: 'https://youtu.be/8S6wPiYDuy4?si=F_9QqNX7rzu_DIFI',
        video2: 'https://www.youtube.com/embed/-hHNGIU3fNA',
    },
    {
        id: 'F0016',
        dia: 3,
        ejercicio: 'ELEVACCIÓN EN PELVIS EN CUADRUPEDA SUPINA',
        series: 3,
        repeticiones: 10,
        volumen_total: 30,
        descanso_entre_series: 60,
        video: 'https://youtu.be/DPtjIDvlJfQ?si=0hWVo0Gtss7uUl8e',
        video2: 'https://www.youtube.com/embed/DPtjIDvlJfQ',
    },
    {
        id: 'F0017',
        dia: 3,
        ejercicio: 'EQUILIBRIO INVERTIDO SOBRE HOMBROS',
        series: 3,
        repeticiones: 10,
        volumen_total: 30,
        descanso_entre_series: 60,
        video: 'https://youtu.be/qUDsU1wPZpA?si=kPR-DoHiFNUdxi1p',
        video2: 'https://www.youtube.com/embed/qUDsU1wPZpA',
    },
    {
        id: 'F0018',
        dia: 3,
        ejercicio: 'PLANCHA HORIZONTAL ISOMETRICA',
        series: 3,
        repeticiones: 12,
        volumen_total: 36,
        descanso_entre_series: 60,
        video: 'https://youtu.be/xdN29y6uZ_A?si=ZtTey8R7h8adY5At',
        video2: 'https://www.youtube.com/embed/xdN29y6uZ_A',
    },
    {
        id: 'F0019',
        dia: 3,
        ejercicio: 'PULLOVER CON MANCUERNA SOBRE PELOTA DE PILATES',
        series: 3,
        repeticiones: 10,
        volumen_total: 30,
        descanso_entre_series: 60,
        video: 'https://youtu.be/1kCRXCrgv_4?si=8jFcg4my2oXAqazp',
        video2: 'https://www.youtube.com/embed/1kCRXCrgv_4',
    },


];



export {
    rutinaFuerza
}
